name: Deploy to GitHub Pages

on:
  push:
    branches:
      - master

defaults:
  run:
    shell: pwsh

jobs:
  deploy:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        dotnet: [5.0.x]

    steps:
    - name: Checkout source
      uses: actions/checkout@v2
    - name: Setup .NET ${{matrix.dotnet}} SDK
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: ${{matrix.dotnet}}
    - name: Install tools
      run: dotnet tool restore
    - name: Validate formatting DevBlogFrontend
      run: dotnet tool run dotnet-format --check
      working-directory: DevBlogFrontend
    - name: Validate formatting PostsListGenerator
      run: dotnet tool run dotnet-format --check
      working-directory: PostsListGenerator
    - name: Install dependencies
      run: dotnet restore
      working-directory: DevBlogFrontend
    - name: Build
      run: dotnet publish --configuration Release --output ../build --no-restore
      working-directory: DevBlogFrontend
    - name: <GH Pages> Bypass Jekyll
      # https://github.blog/2009-12-29-bypassing-jekyll-on-github-pages/
      run: New-Item -Path build/wwwroot/ -Name .nojekyll
    - name: <GH Pages> Set correct base path
      # GH Pages use the repo name as base path.
      run: |
        repo=$(echo $GITHUB_REPOSITORY | sed 's/[^\]*\///')
        sed -i "s/<base href=\"\/\" \/>/<base href=\"\/$repo\/\" \/>/" build/wwwroot/index.html
    - name: <GH Pages> Enable URL routing
      # GH Pages return a 404 page for nested paths.
      # Use the index.html file as a custom 404 page to fix this.
      # GH Pages says 404 > index.html is given > frontend routing is applied as normal.
      run: cp build/wwwroot/index.html build/wwwroot/404.html
    - name: Deploy
      uses: JamesIves/github-pages-deploy-action@4.0.0
      with:
        branch: gh-pages
        folder: build/wwwroot
