name: dotnet package

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        dotnet: [5.0.x]

    steps:
    - name: Checkout source
      uses: actions/checkout@v2
    - name: Setup .NET ${{matrix.dotnet}} SDK
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: ${{matrix.dotnet}}
    - name: Install tools
      run: dotnet tool restore
    - name: Validate formatting DevBlogFrontend
      run: dotnet tool run dotnet-format --check
      working-directory: DevBlogFrontend
    - name: Validate formatting PostsListGenerator
      run: dotnet tool run dotnet-format --check
      working-directory: PostsListGenerator
    - name: Install dependencies
      run: dotnet restore
      working-directory: DevBlogFrontend
    - name: Build
      run: dotnet build --configuration Release --output ../build --no-restore
      working-directory: DevBlogFrontend
