name: dotnet package

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core SDK
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Install dependencies
      run: dotnet restore
      working-directory: DevBlogFrontend
    - name: Build
      run: dotnet build --configuration Release --no-restore
      working-directory: DevBlogFrontend
